policy:
  cherry-pick:
    upstream:
      - github: systemd/systemd
    exception:
      note:
        - 'rhel-only: (feature|bugfix|policy|doc|workaround|ci|test|other)'
        - 'RHEL-only: (feature|bugfix|policy|doc|workaround|ci|test|other)'
  tracker:
    - keyword:
        - 'Resolves: #?'
        - 'Related: #?'
        - 'Reverts: #?'
      type: bugzilla
      issue-format:
        - '\d+$'
      url: 'https://bugzilla.redhat.com/show_bug.cgi?id='
    - keyword:
        - 'Resolves: '
        - 'Related: '
        - 'Reverts: '
      type: jira
      issue-format:
        - 'RHEL-\d+$'
      url: 'https://issues.redhat.com/browse/'
