# doc: https://docs.mergify.com
---

pull_request_rules:
  - name: Add `needs-ci` label on CI fail
    conditions:
      - label!=ci-waived
      - or:
        # Build test
        - -check-success=build (gcc, 10, bfd)
        - -check-success=build (gcc, 11, gold)
        - -check-success=build (clang, 11, bfd)
        - -check-success=build (clang, 12, gold)
        - -check-success=build (clang, 13, lld)
        # Unit tests
        - -check-success=build (GCC, auto)
        - -check-success=build (GCC_ASAN_UBSAN, auto)
        - -check-success=build (CLANG, auto)
        - -check-success=build (CLANG_ASAN_UBSAN, auto)
        - -check-success=build (GCC, openssl)
        - -check-success=build (CLANG, gcrypt)
        # CentOS CI
        - -check-success=CentOS CI (CentOS Stream 9)
        - -check-success=CentOS CI (CentOS Stream 9 + sanitizers)
        # CodeQL
        - -check-success=CodeQL
        # Packit
        - -check-success=rpm-build:centos-stream-9-aarch64
        - -check-success=rpm-build:centos-stream-9-x86_64
        # Other
        - -check-success=Lint Code Base
        - -check-success=Differential ShellCheck
    actions:
      label:
        add:
          - needs-ci

  - name: Remove `needs-ci` label on CI success
    conditions:
      - or:
        - label=ci-waived
        - and:
          # Build test
          - check-success=build (gcc, 10, bfd)
          - check-success=build (gcc, 11, gold)
          - check-success=build (clang, 11, bfd)
          - check-success=build (clang, 12, gold)
          - check-success=build (clang, 13, lld)
          # Unit tests
          - check-success=build (GCC, auto)
          - check-success=build (GCC_ASAN_UBSAN, auto)
          - check-success=build (CLANG, auto)
          - check-success=build (CLANG_ASAN_UBSAN, auto)
          - check-success=build (GCC, openssl)
          - check-success=build (CLANG, gcrypt)
          # CentOS CI
          - check-success=CentOS CI (CentOS Stream 9)
          - check-success=CentOS CI (CentOS Stream 9 + sanitizers)
          # CodeQL
          - check-success=CodeQL
          # Packit
          - check-success=rpm-build:centos-stream-9-aarch64
          - check-success=rpm-build:centos-stream-9-x86_64
          # Other
          - check-success=Lint Code Base
          - check-success=Differential ShellCheck
    actions:
      label:
        remove:
          - needs-ci
