---
# https://github.com/redhat-plumbers-in-action/differential-shellcheck#readme

name: Differential ShellCheck
on:
  pull_request:
    branches:
      - main
      - rhel-9.*.0

permissions:
  contents: read

jobs:
  lint:
    name: Differential ShellCheck
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      pull-requests: write

    steps:
      - name: Repository checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: 0

      - name: Differential ShellCheck
        uses: redhat-plumbers-in-action/differential-shellcheck@11ffc83701635779ecc35f38823ebdd0dca46aae
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
