---
# https://github.com/redhat-plumbers-in-action/differential-shellcheck#readme

name: Differential ShellCheck
on:
  push:
    branches:
      - main
      - rhel-9.*.0
  pull_request:
    branches:
      - main
      - rhel-9.*.0

permissions:
  contents: read

jobs:
  lint:
    name: Differential ShellCheck
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Differential ShellCheck
        uses: redhat-plumbers-in-action/differential-shellcheck@v4
        with:
          # exclude all `.in` files because they may contain unsupported syntax, and they have to be preprocessed first
          exclude-path: '**/*.in'
          token: ${{ secrets.GITHUB_TOKEN }}
